use_frameworks!

platform :ios, '9.0'

target 'ThinningLib_Example' do
  pod 'ThinningLib', :path => '../'

  target 'ThinningLib_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase'
  end
end
